### ISSUE TITLE
convert osgb problem on Ubuntu

### ISSUE THREAD

**Issue by stoneflyop1** [fanvanzh/3dtiles#42]
Hi,
I successfully build 3dtiles on Ubuntu, see #29 .

But when  convert osgb files, it shows a lot of  lines as below:
```
InputStream::readImage(): Unable to find a plugin for jpg
InputStream::readImage(): Unable to find a plugin for jpg
InputStream::readImage(): Unable to find a plugin for jpg
...
```
When the converted tiles files are put into cesium, all are black.

**Comment by stoneflyop1** [comment]
I installed libjpeg and rebuilt osg. It changed to the following error:
```sh
InputStream::readImage(): read error
```

**Comment by fanvanzh** [comment]
you need to build these osbPlugins:
**osgdb_jpeg**
**osgdb_png**

which locate in osgPlugins-3.4.0/

**Comment by fanvanzh** [comment]
the final directory structure is like "3dtile/bin/"

**Comment by stoneflyop1** [comment]
jpeg and png plugin are built, but the error is the same.
i'm using osg3.4.0 now, and there are new errors:
osgPlugins-3.4.0 folder is placed in both "lib" and "bin".
```
InputStream::readImage():
InputStream::readImage():
InputStream::readImage():
InputStream::readObject(): Unsupported wrapper class
InputStream::readObject(): Unsupported wrapper class
InputStream::readObject(): thread 'InputStream::readObject(): Unsupported wrapper class
<unnamed>InputStream::readObject(): Unsupported wrapper class
' panicked at 'InputStream::readObject(): Unsupported wrapper class
thread 'called `Option::unwrap()` on a `None` valueInputStream::readObject(): Unsupported wrapper class
<unnamed>', InputStream::readObject(): Unsupported wrapper class
' panicked at 'libcore/option.rsInputStream::readObject(): Unsupported wrapper class
called `Option::unwrap()` on a `None` value:InputStream::readObject(): Unsupported wrapper class
', 345InputStream::readObject(): Unsupported wrapper class
libcore/option.rs:InputStream::readObject(): Unsupported wrapper class
:21InputStream::readObject(): Unsupported wrapper class
345
thread ':<unnamed>21' panicked at '
called `Option::unwrap()` on a `None` value', libcore/option.rs:345:21
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:511
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:426
   6: rust_begin_unwind
             at libstd/panicking.rs:337
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:92
   8: core::panicking::panic
             at libcore/panicking.rs:53
   9: __rust_maybe_catch_panic
             at /checkout/src/libcore/macros.rs:20
             at libpanic_unwind/gcc.rs:101
             at libpanic_unwind/lib.rs:108
  10: <rayon_core::job::StackJob<L, F, R> as rayon_core::job::Job>::execute
  11: rayon_core::registry::WorkerThread::wait_until_cold
  12: rayon_core::registry::main_loop
  13: std::panicking::try::do_call
  14: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  15: <F as alloc::boxed::FnBox<A>>::call_box
  16: std::sys_common::thread::start_thread
             at /checkout/src/liballoc/boxed.rs:650
             at libstd/sys_common/thread.rs:24
  17: std::sys::unix::thread::Thread::new::thread_start
             at libstd/sys/unix/thread.rs:90
  18: start_thread
  19: clone
stack backtrace:
Rayon: detected unexpected panic; aborting
  Aborted (core dumped)
```

**Comment by fanvanzh** [comment]
where is the "InputStream::readObject".
it seems like from " OsgDB".

use gdb to start the program, and break at "InputStream::readObject" for some detail.

**Comment by stoneflyop1** [comment]
the program is built with header files and shared library, there is no source file for osg here.
the gdb log is as below.
```
(gdb) run
Starting program: /home/jf/dev/3dtiles/target/release/3dtile -f osgb -i /home/jf/LKC_osgb -o /home/jf/osgb_out
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff8ff0700 (LWP 2370)]
[New Thread 0x7ffff8de0700 (LWP 2371)]
[New Thread 0x7ffff87f0700 (LWP 2372)]
[New Thread 0x7ffff81f0700 (LWP 2373)]
[New Thread 0x7ffff7bf0700 (LWP 2374)]
[New Thread 0x7ffff75f0700 (LWP 2375)]
[New Thread 0x7ffff6ff0700 (LWP 2376)]
[New Thread 0x7ffff69f0700 (LWP 2377)]
InputStream::readImage():
InputStream::readImage():
InputStream::readObject():
InputStream::readObject(): Unsupported wrapper class
InputStream::readObject(): InputStream::readObject(): InputStream::readObject(): InputStream::readObject(): InputStream::readObject(): InputStream::readObject(): Unsupported wrapper class
InputStream::readObject(): thread 'InputStream::readObject(): Unsupported wrapper class
<unnamed>InputStream::readObject(): Unsupported wrapper class
thread '' panicked at 'InputStream::readObject(): Unsupported wrapper class
<unnamed>called `Option::unwrap()` on a `None` valueInputStream::readObject(): Unsupported wrapper class
' panicked at '', InputStream::readObject(): Unsupported wrapper class
called `Option::unwrap()` on a `None` valuelibcore/option.rs', thread ':libcore/option.rs<unnamed>345:' panicked at ':345called `Option::unwrap()` on a `None` value21:',
21libcore/option.rs
:345:21
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:511
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:426
   6: rust_begin_unwind
             at libstd/panicking.rs:337
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:92
   8: core::panicking::panic
             at libcore/panicking.rs:53
   9: __rust_maybe_catch_panic
             at /checkout/src/libcore/macros.rs:20
             at libpanic_unwind/gcc.rs:101
             at libpanic_unwind/lib.rs:108
  10: rayon_core::registry::in_worker
  11: rayon::iter::plumbing::bridge_producer_consumer::helper
  12: std::panicking::try::do_call
  13: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  14: <rayon_core::job::StackJob<L, F, R> as rayon_core::job::Job>::execute
  15: rayon_core::registry::WorkerThread::wait_until_cold
  16: rayon_core::registry::main_loop
  17: std::panicking::try::do_call
  18: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  19: <F as alloc::boxed::FnBox<A>>::call_box
  20: std::sys_common::thread::start_thread
             at /checkout/src/liballoc/boxed.rs:650
             at libstd/sys_common/thread.rs:24
  21: std::sys::unix::thread::Thread::new::thread_start
             at libstd/sys/unix/thread.rs:90
  22: start_thread
  23: clone
stack backtrace:
InputStream::readImage():
  InputStream::readObject(): Unsupported wrapper class
 0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:511
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:426
   6: rust_begin_unwind
             at libstd/panicking.rs:337
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:92
   8: core::panicking::panic
             at libcore/panicking.rs:53
   9: __rust_maybe_catch_panic
             at /checkout/src/libcore/macros.rs:20
             at libpanic_unwind/gcc.rs:101
             at libpanic_unwind/lib.rs:108
  10: <rayon_core::job::StackJob<L, F, R> as rayon_core::job::Job>::execute
  11: rayon_core::registry::WorkerThread::wait_until_cold
  12: rayon_core::registry::main_loop
  13: std::panicking::try::do_call
  14: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  15: <F as alloc::boxed::FnBox<A>>::call_box
  16: std::sys_common::thread::start_thread
             at /checkout/src/liballoc/boxed.rs:650
             at libstd/sys_common/thread.rs:24
  17: std::sys::unix::thread::Thread::new::thread_start
             at libstd/sys/unix/thread.rs:90
  18: start_thread
  19: clone
Rayon: detected unexpected panic; aborting
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:511
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:426
   6: rust_begin_unwind
             at libstd/panicking.rs:337
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:92

Thread 6 "3dtile" received signal SIGABRT, Aborted.
[Switching to Thread 0x7ffff7bf0700 (LWP 2374)]
0x00007ffffc885428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
54      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
```

**Comment by fanvanzh** [comment]
look like Plugins "osgdb_jpeg" is miss.
try build from source, and debug the detail.

**Comment by stoneflyop1** [comment]
i installed osg deps using the below command, and rebuild osg, everything is ok now. Thanks.
```
apt-get build-dep openscenegraph
cmake . -DFFMPEG_LIBAVCODEC_INCLUDE_DIRS=""
make
```
